#!/bin/bash

relative_path='files/'

for letter in {65..90}
do 
    pattern=$relative_path$(printf '%b' $(printf '\\%03o' $letter))'*';
    dir=$(printf '%b' $(printf '\\%03o' $letter));
    mv $pattern $dir;
done

for letter in {97..122}
do 
    pattern=$relative_path$(printf '%b' $(printf '\\%03o' $letter))'*';
    small_letter=$(($letter-32));
    dir=$(printf '%b' $(printf '\\%03o' $small_letter));
    mv $pattern $dir;
done
